### PR TITLE
[#31] test: add tests for TimeValidator

### LINKED ISSUE #31: add unit tests for TimeValidator methods
need unit tests for `TimeValidator`

### PR DESCRIPTION
**Pull request by Chaitanya134**
Added Tests for TimeValidator's validator method

closes #31

### CODE REVIEW

**Review by sudiptob2 — CHANGES_REQUESTED** [review]
Thanks much for the PR :pray: 

- I am already using `pytest`, can you please use `pytest` for writing your test cases?

    you can use `with pytest.raises(SystemExit):`  in pytest.

- Also could you please rename folder `tests/validator` into `tests/test_validator` :+1:

**Comment by Chaitanya134** [comment]
Did the changes :)
Kindly review
Haven't used pytest before so I don't know if this is fine

**Comment by sudiptob2** [comment]
> 

Hey, seems OK for now :rocket: But some of my own tests are broken, I need to fix those. Also, I am gonna implement a CI pipeline to run these tests and some additional code quality checks. I think it is high time I implement that. So please give me a couple of days and I will review your changes and possibly merge if everything is OK :pray:

**Comment by Chaitanya134** [comment]
Sure :)

**Comment by sudiptob2** [comment]
I have implemented a script `check.sh` for code quality check and all. can you please check your changes with that :pray: you will find it in `.github/check.sh` @Chaitanya134

**Review by sudiptob2 — APPROVED** [review]

**Pull request merged**
