### PR TITLE
fixed spelling errors in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jaygala223**
Fixed the spelling of 'convention' throughout the document.

### CODE REVIEW

**Review by sudiptob2 — COMMENTED** [review]
Thanks :rocket: 
Can you please update the `contributing.md` more? Add a section called **Example**. There add some examples of the branch names, commit messages etc.
Take example from previous commits that I have made.

**Comment by jaygala223** [comment]
Sure. I'll get started on that.

**Comment by jaygala223** [comment]
Sorry, I accidentally created a new pull request. Here's the link: https://github.com/sudiptob2/leet-easy/pull/45

**Comment by sudiptob2** [comment]
Similar pull req at #45

**Pull request closed without merging**
