### PR TITLE
wip: github actions to run tests

### PR DESCRIPTION
**Pull request by nilesh05apr**
Implement a github action to check unit tests #33

### CODE REVIEW

**Review by sudiptob2 — COMMENTED** [review]
Thanks for the effort :pray:  but this action is not complete and I can see its not even running properly. Can you please try to improve this, I think its not ready for merge yet.

**Comment by nilesh05apr** [comment]
Yes I am working on it.

**Comment by nilesh05apr** [comment]
@sudiptob2  there is some problem running the test scripts.
>       challenge = RequestParser.parse()
E       TypeError: parse() missing 1 required positional argument: 'challenge_info'

can you please assist me.
thanks

**Comment by nilesh05apr** [comment]
Hello @sudiptob2  I have fixed the issue by adding appropriate arguments to the parse(). All tests are passing and running on github actions can you please review the PR.
Thanks

**Comment by sudiptob2** [comment]
> can you please assist me
Great :+1:  I had already updated the tests, please update your branch. I will help you to updated the workflow in the subsequent conversations. I have also implemented a `check.sh` script that I want to run in the ci. you can take a look at that

**Comment by sudiptob2** [comment]
It shows changes in 14 files, now it's difficult to review. Maybe there have gone something wrong while you resynced the main branch. Can you check it out? Also its OK if you make a fresh PR.

**Comment by nilesh05apr** [comment]
yeah i was suggesting same. it got clumsy. i will start a fresh new pr.

**Comment by sudiptob2** [comment]
similar PR at #46

**Pull request closed without merging**
